xcodeproj 'Pdef Tests'
workspace '../Pdef'
inhibit_all_warnings!

def import_pods
  pod 'Pdef', :path => '../Pdef.podspec'
  pod 'OCMock'
end

target :ios do
  platform :ios, '6.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.8'
  link_with 'OSX Tests'
  import_pods
end

