// Generated by Pdef Objective-C generator.

#import "Base.h"
#import "Subtype.h"
#import "Subtype2.h"
#import "MultiLevelSubtype.h"


@implementation Base {
    BOOL _type_isset;
    BOOL _field_isset;
}
static PDMessageDescriptor *_BaseDescriptor;

// type
- (BOOL)hasType {
    return _type_isset;
}

- (void)setType:(PolymorphicType )type {
    _type = type;
    _type_isset = YES;
}

- (void)clearType {
    _type_isset = NO;
}

// field
- (BOOL)hasField {
    return _field_isset;
}

- (void)setField:(NSString *)field {
    _field = field;
    _field_isset = YES;
}

- (void)clearField {
    _field = nil;
    _field_isset = NO;
}


- (PDMessageDescriptor *)descriptor {
    return [Base typeDescriptor];
}

+ (PDMessageDescriptor *)typeDescriptor {
    return _BaseDescriptor;
}

+ (void)initialize {
    if (self != [Base class]) {
        return;
    }

    _BaseDescriptor = [[PDMessageDescriptor alloc]
            initWithClass:[Base class]
                     base:nil
       discriminatorValue:0
         subtypeSuppliers:@[
                           ^PDMessageDescriptor *() { return [Subtype typeDescriptor]; },
                           ^PDMessageDescriptor *() { return [Subtype2 typeDescriptor]; },
                           ^PDMessageDescriptor *() { return [MultiLevelSubtype typeDescriptor]; },
                          ]
                   fields:@[
    [[PDFieldDescriptor alloc] initWithName:@"type" typeSupplier:^PDDataTypeDescriptor *() { return PolymorphicTypeDescriptor(); } discriminator:YES],
    [[PDFieldDescriptor alloc] initWithName:@"field" typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; } discriminator:NO],
                           ]];
}
@end


