// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"
@class Subtype;
@class Subtype2;
@class MultiLevelSubtype;
#import "PolymorphicType.h"


/** Base polymorphic message.
@field discriminator    Discriminator field set in all subclasses.
 */
@interface Base : NSObject
@property (nonatomic) PolymorphicType type;
@property (nonatomic) NSString *field;

+ (PDMessageDescriptor *)typeDescriptor;
@end


