// Generated by Pdef Objective-C generator.

#import "PDef.h"


// Descriptors.
PDEnumDescriptor *PolymorphicTypeDescriptor();
PDMessageDescriptor *BaseDescriptor();
PDMessageDescriptor *SubtypeDescriptor();
PDMessageDescriptor *Subtype2Descriptor();
PDMessageDescriptor *MultiLevelSubtypeDescriptor();
