// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "MessagesDescriptors.h"

@class Base;


/** Enum.
Multi-line comment.
 */
typedef NS_ENUM(NSInteger, TestEnum) {
    TestEnum_ONE,
    TestEnum_TWO,
    TestEnum_THREE,
};


/** Simple message.
Multi-line comment.
 */
@interface TestMessage : NSObject
@property (nonatomic) NSString *string0;
@property (nonatomic) NSNumber *bool0;
@property (nonatomic) NSNumber *int0;
@end


/** Message with fields of all data types. */
@interface TestComplexMessage : TestMessage
@property (nonatomic) NSNumber *short0;
@property (nonatomic) NSNumber *long0;
@property (nonatomic) NSNumber *float0;
@property (nonatomic) NSNumber *double0;
@property (nonatomic) NSDate *datetime0;
@property (nonatomic) NSArray *list0;
@property (nonatomic) NSSet *set0;
@property (nonatomic) NSDictionary *map0;
@property (nonatomic) TestEnum enum0;
@property (nonatomic) TestMessage *message0;
@property (nonatomic) Base *polymorphic;
@property (nonatomic) TestComplexMessage *datatypes;
@end


