// Generated by Pdef Objective-C generator.

#import "PDef.h"


// Descriptors.
PDEnumDescriptor *TestEnumDescriptor();
PDMessageDescriptor *TestMessageDescriptor();
PDMessageDescriptor *TestComplexMessageDescriptor();
