// Generated by Pdef Objective-C generator.

#import "MultiLevelSubtype.h"
#import "Subtype.h"


@implementation MultiLevelSubtype
static PDMessageDescriptor *_MultiLevelSubtypeDescriptor;

+ (PDMessageDescriptor *)typeDescriptor {
    return _MultiLevelSubtypeDescriptor;
}

- (PDMessageDescriptor *)descriptor {
    return [MultiLevelSubtype typeDescriptor];
}

- (id) init {
    if (self = [super init]) {
        self.type = PolymorphicType_MULTILEVEL_SUBTYPE ;
    }
    return self;
}

- (BOOL)isEqualToMessage:(PDMessage *)message {
    if (self == message)
        return YES;
    if (message == nil)
        return NO;
    if (![[message class] isEqual:[self class]])
        return NO;
    if (![super isEqualToMessage:message])
        return NO;

    MultiLevelSubtype *cast = (MultiLevelSubtype *)message;
    if (self.mfield != cast.mfield && ![self.mfield isEqual:cast.mfield])
        return NO;
    return YES;
}

- (NSUInteger)hash {
    NSUInteger hash = [super hash];
    hash = hash * 31u + [self.mfield hash];
    return hash;
}

- (id)copyWithZone:(NSZone *)zone {
    MultiLevelSubtype *copy = (MultiLevelSubtype *)[super copyWithZone:zone];

    if (copy != nil) {
        copy.mfield = _mfield;
    }

    return copy;
}

+ (void)initialize {
    if (self != [MultiLevelSubtype class]) {
        return;
    }

    _MultiLevelSubtypeDescriptor = [[PDMessageDescriptor alloc]
            initWithClass:[MultiLevelSubtype class]
                     base:[Subtype typeDescriptor]
       discriminatorValue:PolymorphicType_MULTILEVEL_SUBTYPE 
         subtypeSuppliers:@[]
                   fields:@[
    [[PDFieldDescriptor alloc] initWithName:@"mfield" typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; } discriminator:NO],
                           ]];
}
@end


