// Generated by Pdef Objective-C generator.

#import "MultiLevelSubtype.h"
#import "Subtype.h"


@implementation MultiLevelSubtype
static PDMessageDescriptor *_MultiLevelSubtypeDescriptor;

+ (PDMessageDescriptor *)typeDescriptor {
    return _MultiLevelSubtypeDescriptor;
}

- (PDMessageDescriptor *)descriptor {
    return [MultiLevelSubtype typeDescriptor];
}

- (id) init {
    if (self = [super init]) {
        self.type = PolymorphicType_MULTILEVEL_SUBTYPE ;
    }
    return self;
}

- (id)copyWithZone:(NSZone *)zone {
    MultiLevelSubtype *copy = [[[self class] allocWithZone:zone] init];

    if (copy != nil) {
        copy.mfield = _mfield;
    }

    return copy;
}

+ (void)initialize {
    if (self != [MultiLevelSubtype class]) {
        return;
    }

    _MultiLevelSubtypeDescriptor = [[PDMessageDescriptor alloc]
            initWithClass:[MultiLevelSubtype class]
                     base:[Subtype typeDescriptor]
       discriminatorValue:PolymorphicType_MULTILEVEL_SUBTYPE 
         subtypeSuppliers:@[]
                   fields:@[
    [[PDFieldDescriptor alloc] initWithName:@"mfield" typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; } discriminator:NO],
                           ]];
}
@end


