// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"


/** Enum with discriminator values. */
typedef NS_ENUM(NSInteger, PolymorphicType) {
    PolymorphicType_SUBTYPE,
    PolymorphicType_SUBTYPE2,
    PolymorphicType_MULTILEVEL_SUBTYPE,
};

PDEnumDescriptor *PolymorphicTypeDescriptor();


