// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"
#import "Base.h"
#import "PolymorphicType.h"


@interface Subtype2 : Base
@property (nonatomic) NSString *subfield2;

+ (PDMessageDescriptor *)typeDescriptor;
@end


