// Generated by Pdef Objective-C generator.

#import "Subtype2.h"
#import "Base.h"


@implementation Subtype2
static PDMessageDescriptor *_Subtype2Descriptor;

+ (PDMessageDescriptor *)typeDescriptor {
    return _Subtype2Descriptor;
}

- (PDMessageDescriptor *)descriptor {
    return [Subtype2 typeDescriptor];
}

- (id) init {
    if (self = [super init]) {
        self.type = PolymorphicType_SUBTYPE2 ;
    }
    return self;
}

- (BOOL)isEqualToMessage:(PDMessage *)message {
    if (self == message)
        return YES;
    if (message == nil)
        return NO;
    if (![[message class] isEqual:[self class]])
        return NO;
    if (![super isEqualToMessage:message])
        return NO;

    Subtype2 *cast = (Subtype2 *)message;
    if (self.subfield2 != cast.subfield2 && ![self.subfield2 isEqual:cast.subfield2])
        return NO;
    return YES;
}

- (NSUInteger)hash {
    NSUInteger hash = [super hash];
    hash = hash * 31u + [self.subfield2 hash];
    return hash;
}

- (id)copyWithZone:(NSZone *)zone {
    Subtype2 *copy = (Subtype2 *)[super copyWithZone:zone];

    if (copy != nil) {
        copy.subfield2 = _subfield2;
    }

    return copy;
}

+ (void)initialize {
    if (self != [Subtype2 class]) {
        return;
    }

    _Subtype2Descriptor = [[PDMessageDescriptor alloc]
            initWithClass:[Subtype2 class]
                     base:[Base typeDescriptor]
       discriminatorValue:PolymorphicType_SUBTYPE2 
         subtypeSuppliers:@[]
                   fields:@[
    [[PDFieldDescriptor alloc] initWithName:@"subfield2" typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; } discriminator:NO],
                           ]];
}
@end


