// Generated by Pdef Objective-C generator.

#import "Subtype.h"
#import "Base.h"
#import "MultiLevelSubtype.h"


@implementation Subtype
static PDMessageDescriptor *_SubtypeDescriptor;

+ (PDMessageDescriptor *)typeDescriptor {
    return _SubtypeDescriptor;
}

- (PDMessageDescriptor *)descriptor {
    return [Subtype typeDescriptor];
}

+ (void)initialize {
    if (self != [Subtype class]) {
        return;
    }

    _SubtypeDescriptor = [[PDMessageDescriptor alloc]
            initWithClass:[Subtype class]
                     base:[Base typeDescriptor]
       discriminatorValue:PolymorphicType_SUBTYPE 
         subtypeSuppliers:@[
                           ^PDMessageDescriptor *() { return [MultiLevelSubtype typeDescriptor]; },
                          ]
                   fields:@[
    [[PDFieldDescriptor alloc] initWithName:@"subfield" typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; } discriminator:NO],
                           ]];
}
@end


