// Generated by Pdef Objective-C generator.

#import "Subtype2.h"
#import "Base.h"


@implementation Subtype2
static PDMessageDescriptor *_Subtype2Descriptor;

+ (PDMessageDescriptor *)typeDescriptor {
    return _Subtype2Descriptor;
}

- (PDMessageDescriptor *)descriptor {
    return [Subtype2 typeDescriptor];
}

- (id) init {
    if (self = [super init]) {
        self.type = PolymorphicType_SUBTYPE2 ;
    }
    return self;
}

+ (void)initialize {
    if (self != [Subtype2 class]) {
        return;
    }

    _Subtype2Descriptor = [[PDMessageDescriptor alloc]
            initWithClass:[Subtype2 class]
                     base:[Base typeDescriptor]
       discriminatorValue:PolymorphicType_SUBTYPE2 
         subtypeSuppliers:@[]
                   fields:@[
    [[PDFieldDescriptor alloc] initWithName:@"subfield2" typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; } discriminator:NO],
                           ]];
}
@end


