// Generated by Pdef Objective-C generator.

#import "TestException.h"


@implementation TestException {
    BOOL _text_isset;
}
static PDMessageDescriptor *_TestExceptionDescriptor;

// text
- (BOOL)hasText {
    return _text_isset;
}

- (void)setText:(NSString *)text {
    _text = text;
    _text_isset = YES;
}

- (void)clearText {
    _text = nil;
    _text_isset = NO;
}


- (PDMessageDescriptor *)descriptor {
    return [TestException typeDescriptor];
}

+ (PDMessageDescriptor *)typeDescriptor {
    return _TestExceptionDescriptor;
}

+ (void)initialize {
    if (self != [TestException class]) {
        return;
    }

    _TestExceptionDescriptor = [[PDMessageDescriptor alloc]
            initWithClass:[TestException class]
                     base:nil
       discriminatorValue:0
         subtypeSuppliers:@[]
                   fields:@[
    [[PDFieldDescriptor alloc] initWithName:@"text" typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; } discriminator:NO],
                           ]];
}
@end


