// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"


/** Simple message.
Multi-line comment.
 */
@interface TestMessage : PDMessage
@property (nonatomic) NSString *string0;
@property (nonatomic) NSNumber *bool0;
@property (nonatomic) NSNumber *int0;

- (BOOL) hasString0;
- (void) clearString0;

- (BOOL) hasBool0;
- (void) clearBool0;

- (BOOL) hasInt0;
- (void) clearInt0;


+ (PDMessageDescriptor *)typeDescriptor;
@end


