// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"


/** Simple message.
Multi-line comment.
 */
@interface TestMessage : NSObject
@property (nonatomic) NSString *string0;
@property (nonatomic) NSNumber *bool0;
@property (nonatomic) NSNumber *int0;

+ (PDMessageDescriptor *)typeDescriptor;
@end


