// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"
@class TestException;
@class TestMessage;
@class TestMessage;


/** Test interface with method of all types.
Multi-line comment.
 */
@protocol TestInterface
/** Returns the sum of the numbers.
Multi-line comment.
 */
- (NSOperation *) methodArg0:(int32_t )arg0
        arg1:(int32_t )arg1
            response:(void (^)(id result, NSError *error))response;

/** Returns the sum of the numbers. */
- (NSOperation *) queryArg0:(int32_t )arg0
        arg1:(int32_t )arg1
            response:(void (^)(id result, NSError *error))response;

/** Returns the sum of the numbers. */
- (NSOperation *) postArg0:(int32_t )arg0
        arg1:(int32_t )arg1
            response:(void (^)(id result, NSError *error))response;

/** Returns the same string. */
- (NSOperation *) string0Text:(NSString *)text
            response:(void (^)(id result, NSError *error))response;

/** Return the same datetime. */
- (NSOperation *) datetime0Dt:(NSDate *)dt
            response:(void (^)(id result, NSError *error))response;

/** Returns the same message. */
- (NSOperation *) message0Msg:(TestMessage *)msg
            response:(void (^)(id result, NSError *error))response;

/** Returns the total number of items. */
- (NSOperation *) collectionsList0:(NSArray *)list0
        set0:(NSSet *)set0
        map0:(NSDictionary *)map0
            response:(void (^)(id result, NSError *error))response;

/** Returns the same interface (yes, it's endless). */
- (id<TestInterface> ) interface0Arg0:(int32_t )arg0
        arg1:(int32_t )arg1
;

/** Void method which returns null. */
- (NSOperation *) void0Response:(void (^)(id result, NSError *error))response;

/** Throws a TestException. */
- (NSOperation *) exc0Response:(void (^)(id result, NSError *error))response;

/** Throws any server error. */
- (NSOperation *) serverErrorResponse:(void (^)(id result, NSError *error))response;

@end

@interface TestInterfaceClient : PDInterface <TestInterface>
@end
PDInterfaceDescriptor *TestInterfaceDescriptor();
