// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"


/** Test exception.
Multi-line comment.
 */
@interface TestException : NSObject
@property (nonatomic) NSString *text;

+ (PDMessageDescriptor *)typeDescriptor;
@end


