// Generated by Pdef Objective-C generator.

#import "TestComplexMessage.h"
#import "TestMessage.h"
#import "TestMessage.h"
#import "Base.h"


@implementation TestComplexMessage
static PDMessageDescriptor *_TestComplexMessageDescriptor;

+ (PDMessageDescriptor *)typeDescriptor {
    return _TestComplexMessageDescriptor;
}

- (PDMessageDescriptor *)descriptor {
    return [TestComplexMessage typeDescriptor];
}

+ (void)initialize {
    if (self != [TestComplexMessage class]) {
        return;
    }

    _TestComplexMessageDescriptor = [[PDMessageDescriptor alloc]
            initWithClass:[TestComplexMessage class]
                     base:[TestMessage typeDescriptor]
       discriminatorValue:0
         subtypeSuppliers:@[]
                   fields:@[
                           [[PDFieldDescriptor alloc] initWithName:@"short0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors int16]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"long0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors int64]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"float0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors float0]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"double0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors double0]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"datetime0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors datetime]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"list0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors listWithElement:[PDDescriptors int32]]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"set0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors setWithElement:[PDDescriptors int32]]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"map0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors mapWithKey:[PDDescriptors int32] value:[PDDescriptors float0]]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"enum0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return TestEnumDescriptor(); }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"message0"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [TestMessage typeDescriptor]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"polymorphic"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [Base typeDescriptor]; }
                                isDiscriminator:NO],
                           [[PDFieldDescriptor alloc] initWithName:@"datatypes"
                                   typeSupplier:^PDDataTypeDescriptor *() { return [TestComplexMessage typeDescriptor]; }
                                isDiscriminator:NO],
                           ]];
}
@end


