// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "PDef.h"


/** Enum.
Multi-line comment.
 */
typedef NS_ENUM(NSInteger, TestEnum) {
    TestEnum_ONE,
    TestEnum_TWO,
    TestEnum_THREE,
};

PDEnumDescriptor *TestEnumDescriptor();


