// Generated by Pdef Objective-C generator.

#import <Foundation/Foundation.h>
#import "InheritanceDescriptors.h"



/** Enum with discriminator values. */
typedef NS_ENUM(NSInteger, PolymorphicType) {
    PolymorphicType_SUBTYPE,
    PolymorphicType_SUBTYPE2,
    PolymorphicType_MULTILEVEL_SUBTYPE,
};


/** Base polymorphic message.
@field discriminator    Discriminator field set in all subclasses.
 */
@interface Base : NSObject
@property (nonatomic) PolymorphicType type;
@property (nonatomic) NSString *field;
@end


@interface Subtype : Base
@property (nonatomic) NSString *subfield;
@end


@interface Subtype2 : Base
@property (nonatomic) NSString *subfield2;
@end


@interface MultiLevelSubtype : Subtype
@property (nonatomic) NSString *mfield;
@end


