// Generated by Pdef Objective-C generator.

#import "Interfaces.h"
#import "MessagesDescriptors.h"


@implementation TestException
- (PDMessageDescriptor *)descriptor {
    return TestExceptionDescriptor();
}
@end


// Descriptors
static dispatch_once_t _TestExceptionOnce;
static PDMessageDescriptor *_TestExceptionDescriptor;
PDMessageDescriptor *TestExceptionDescriptor() {
    dispatch_once(&_TestExceptionOnce, ^() {
        _TestExceptionDescriptor = [[PDMessageDescriptor alloc]
                initWithClass:[TestException class]
                         base:nil
           discriminatorValue:0
             subtypeSuppliers:@[]
                       fields:@[
                               [[PDFieldDescriptor alloc] initWithName:@"text"
                                       typeSupplier:^PDDataTypeDescriptor *() { return [PDDescriptors string]; }
                                    isDiscriminator:NO],
                               ]];
    });
    return _TestExceptionDescriptor;
}


